/** French source copy and its English equivalent for the public site. */
export const english: Record<string, string> = {
  // Shared navigation and footer
  "CABINET VÉTÉRINAIRE": "VETERINARY CLINIC",
  "Cabinet Vétérinaire Atlas Marrakech": "Atlas Veterinary Clinic Marrakech",
  "Cabinet Vétérinaire · Marrakech": "Veterinary Clinic · Marrakech",
  "Accueil": "Home",
  "À propos": "About",
  "Prendre RDV": "Book appointment",
  "Prendre rendez-vous": "Book an appointment",
  "Prendre rendez-vous en ligne": "Book an appointment online",
  "Demander un rendez-vous": "Request an appointment",
  "Navigation Rapide": "Quick links",
  "Tous nos services & soins": "All our services and care",
  "Pourquoi choisir Atlas": "Why choose Atlas",
  "Plan d'accès & contact": "Directions and contact",
  "Coordonnées & Urgences": "Contact and emergencies",
  "Lun - Sam : Sur rendez-vous": "Mon–Sat: By appointment",
  "En cas d’urgence, appelez avant de venir": "In an emergency, call before coming",
  "Tous droits réservés.": "All rights reserved.",
  "Cabinet Vétérinaire Atlas Marrakech. Tous droits réservés.": "Atlas Veterinary Clinic Marrakech. All rights reserved.",
  "Soigner avec science, écoute et bienveillance.": "Care with science, attention and compassion.",
  "Besoin d'aide ? WhatsApp": "Need help? WhatsApp",
  "NUMÉRO D’URGENCE": "EMERGENCY NUMBER",
  "Fermer la barre d’urgence": "Close emergency banner",
  "Contacter le Cabinet Vétérinaire Atlas sur WhatsApp": "Contact Atlas Veterinary Clinic on WhatsApp",
  "Écrire sur WhatsApp": "Message us on WhatsApp",
  "WhatsApp Direct": "WhatsApp us",
  "Médecine vétérinaire moderne, préventive et bienveillante à Marrakech. Plateau médical proposant consultation, radiologie, chirurgie et prise en charge des urgences.": "Modern, preventive and compassionate veterinary medicine in Marrakech. Our clinic offers consultations, radiology, surgery and emergency care.",
  // Home hero and sections
  "Cabinet vétérinaire à Marrakech": "Veterinary clinic in Marrakech",
  "Pour eux,": "For them,",
  "chaque attention compte.": "every act of care matters.",
  "Au": "At",
  "Cabinet Vétérinaire Atlas": "Atlas Veterinary Clinic",
  ", nous accompagnons la santé de votre animal": ", we support your pet's health",
  "avec écoute, des soins adaptés et un contact simple avec notre équipe.": "with attentive listening, tailored care and easy access to our team.",
  "Une urgence ?": "An emergency?",
  "Appelez avant de venir :": "Call before coming:",
  "9 prestations": "9 services",
  "Du bilan de santé à la garde": "From checkups to pet boarding",
  "À Marrakech": "In Marrakech",
  "Près de SINKO, avenue Mouzdalifa": "Near SINKO, Mouzdalifa Avenue",
  "Rendez-vous en ligne": "Online appointments",
  "Demande simple, confirmation par le cabinet": "Easy request, confirmed by the clinic",
  "Nos prestations": "Our services",
  "Les soins dont votre animal a besoin.": "The care your pet needs.",
  "Voir tous les services": "View all services",
  "Voir les 9 services": "View all 9 services",
  "Consultation": "Consultation",
  "Hospitalisation": "Hospitalization",
  "Urgences": "Emergencies",
  "Radiologie": "Radiology",
  "Analyses biologiques": "Laboratory tests",
  "Chirurgie": "Surgery",
  "Toilettage": "Grooming",
  "Garde": "Pet boarding",
  "Dentisterie": "Dentistry",
  "Un examen et des conseils adaptés à votre animal.": "An examination and advice tailored to your pet.",
  "Des soins suivis lorsque son état le nécessite.": "Ongoing care when your pet needs it.",
  "Appelez le cabinet avant de vous déplacer.": "Call the clinic before coming.",
  "Des examens d'imagerie pour orienter le diagnostic.": "Imaging tests to help guide a diagnosis.",
  "Des analyses pour éclairer les décisions de soin.": "Tests to inform care decisions.",
  "Une prise en charge selon l'évaluation vétérinaire.": "Care based on a veterinary assessment.",
  "Des soins d'hygiène pour votre compagnon.": "Hygiene care for your companion.",
  "Une solution pendant vos absences, selon disponibilité.": "Care while you are away, subject to availability.",
  "Des soins pour préserver sa santé bucco-dentaire.": "Care to protect your pet's oral health.",
  "Notre approche": "Our approach",
  "À propos du cabinet": "About the clinic",
  "Découvrir le cabinet": "Discover the clinic",
  "À leurs côtés,": "By their side,",
  "à chaque étape.": "at every stage.",
  "Au Cabinet Vétérinaire Atlas à Marrakech, nous accueillons votre compagnon avec attention et vous accompagnons avec des soins adaptés et des explications claires.": "At Atlas Veterinary Clinic in Marrakech, we welcome your companion with care and support you with tailored treatment and clear explanations.",
  "Au Cabinet Vétérinaire Atlas à Marrakech, nous accueillons votre": "At Atlas Veterinary Clinic in Marrakech, we welcome your",
  "compagnon avec attention et vous accompagnons avec des soins": "companion with care and support you with tailored treatment",
  "adaptés et des explications claires.": "and clear explanations suited to your pet's needs.",
  "Une visite attentive, du premier échange au suivi.": "Attentive care, from the first conversation to follow-up.",
  "Chaque animal a son histoire. Nous commençons par écouter vos observations, puis nous examinons votre compagnon pour proposer les soins qui correspondent à son état.": "Every pet has a story. We first listen to your observations, then examine your companion and recommend care suited to their condition.",
  "Nous vous expliquons ce que nous observons et les prochaines étapes, afin que vous puissiez prendre des décisions éclairées pour sa santé.": "We explain what we observe and the next steps so you can make informed decisions about your pet's health.",
  "Des échanges simples et directs avec l'équipe": "Open, direct conversations with the team",
  "Une prise en charge adaptée aux besoins de l'animal": "Care tailored to your pet's needs",
  "Ce qui nous guide": "What guides us",
  "Une relation de confiance, à chaque visite.": "A trusting relationship at every visit.",
  "Écouter": "Listen",
  "Vos observations et les habitudes de votre animal nous aident à comprendre ses besoins.": "Your observations and your pet's habits help us understand their needs.",
  "Examiner": "Examine",
  "Chaque soin commence par une évaluation attentive de l'état de votre compagnon.": "Every treatment begins with a careful assessment of your companion's condition.",
  "Expliquer": "Explain",
  "Nous prenons le temps de répondre à vos questions et de vous présenter les prochaines étapes.": "We take time to answer your questions and explain the next steps.",
  "Nous sommes là pour vous et votre compagnon.": "We are here for you and your companion.",
  "Nous contacter": "Contact us",
  "Vétérinaire examinant un chat": "Veterinarian examining a cat",
  "Vétérinaire auscultant un chien": "Veterinarian examining a dog",
  "Chat persan roux assis sur un comptoir": "Ginger Persian cat sitting on a counter",
  "Une visite claire et attentive, pour vous comme pour lui.": "A clear, attentive visit for you and your pet.",
  "Chaque animal a son histoire. Nous prenons le temps d'écouter vos observations, d'examiner votre compagnon et de vous expliquer les prochaines étapes.": "Every pet has a story. We take time to listen to your observations, examine your companion and explain the next steps.",
  "Un échange sur les besoins de votre animal": "A conversation about your pet's needs",
  "Des soins proposés selon son état": "Care suited to your pet's condition",
  "Des réponses à vos questions avant de repartir": "Answers to your questions before you leave",
  "Témoignages": "Testimonials",
  "Ils nous confient leurs compagnons.": "They trust us with their companions.",
  "Votre expérience compte. Partagez votre avis sur Google après votre visite au cabinet.": "Your experience matters. Share a Google review after your visit.",
  "Laisser un avis sur Google": "Leave a Google review",
  "Lire les avis sur Google Maps": "Read reviews on Google Maps",
  "Activez JavaScript pour afficher les avis Google dans cette section.": "Enable JavaScript to see Google reviews here.",
  "Nous trouver": "Find us",
  "Votre cabinet vétérinaire à Marrakech.": "Your veterinary clinic in Marrakech.",
  "Adresse et contact": "Address and contact",
  // Gallery
  "Galerie": "Gallery",
  "Retour à l'accueil": "Back to home",
  "L'excellence en images.": "Excellence in pictures.",
  "Découvrez tous les moments présentés dans notre galerie.": "Discover all the moments featured in our gallery.",
  "Des instants de douceur et de complicité avec les animaux qui nous inspirent chaque jour.": "Gentle moments and special bonds with the animals who inspire us every day.",
  "Explorer la Galerie": "Explore the gallery",
  "Fermer la photo": "Close photo",
  "Photo précédente": "Previous photo",
  "Photo suivante": "Next photo",
  "Chat roux dans le cabinet": "Ginger cat in the clinic",
  "Chien et chat au repos": "Dog and cat resting",
  "Chien dans un espace d'accueil": "Dog in a reception area",
  "Chien et chat ensemble": "Dog and cat together",
  "Chat pendant un examen vétérinaire": "Cat during a veterinary examination",
  "Chien et chat à l'extérieur": "Dog and cat outdoors",
  "Chat pendant une échographie": "Cat during an ultrasound scan",
  "Chien et chat sur un canapé": "Dog and cat on a sofa",
  "Chien et chat au cabinet": "Dog and cat at the clinic",
  "Chien et chat dans la nature": "Dog and cat outdoors",
  "Portrait d'un chat roux": "Portrait of a ginger cat",
  "Chien avec un vétérinaire": "Dog with a veterinarian",
  // Services page
  "Des soins complets.": "Complete care.",
  "À chaque étape.": "At every stage.",
  "Prévenir, comprendre, soigner. Une attention adaptée à votre compagnon,": "Prevent, understand and treat. Care tailored to your companion,",
  "des premières consultations aux soins du quotidien.": "from the first consultation to everyday care.",
  "Prévenir, comprendre, soigner. Une attention adaptée à votre compagnon, des premières consultations aux soins du quotidien.": "Prevent, understand and treat. Care tailored to your companion, from the first consultation to everyday care.",
  "Découvrir nos prestations": "Explore our services",
  "Accès aux catégories de soins": "Care categories",
  "Médecine": "Medicine",
  "Consultation & suivi": "Consultations and follow-up",
  "Diagnostic": "Diagnostics",
  "Imagerie & analyses": "Imaging and tests",
  "Interventions & soins": "Procedures and care",
  "Bien-être": "Wellness",
  "Hygiène & confort": "Hygiene and comfort",
  "Nos pôles de compétences": "Our areas of expertise",
  "Le bon soin, au bon moment.": "The right care at the right time.",
  "Découvrez l'ensemble des prestations dispensées au Cabinet Vétérinaire Atlas.": "Explore all the services offered at Atlas Veterinary Clinic.",
  "Comprendre & prévenir": "Understand and prevent",
  "Du premier examen aux analyses, pour orienter les soins de votre animal.": "From the first examination to testing, to guide your pet's care.",
  "Soigner & accompagner": "Treat and support",
  "Une prise en charge adaptée lorsque votre compagnon a besoin de soins.": "Tailored support when your companion needs care.",
  "Prendre soin au quotidien": "Everyday care",
  "Hygiène, confort et garde : des attentions pour chaque étape de sa vie.": "Hygiene, comfort and boarding at every stage of life.",
  "3 prestations": "3 services",
  "Un examen clinique minutieux pour dépister, soigner et conseiller à chaque étape de vie.": "A thorough clinical examination to assess, treat and advise at every life stage.",
  "Bilan de santé approfondi": "Comprehensive health check",
  "Vaccinations & antiparasitaires": "Vaccinations and parasite prevention",
  "Conseils nutritionnels personnalisés": "Personalized nutrition advice",
  "Si votre animal présente des symptômes inquiétants, appelez le cabinet avant de vous déplacer.": "If your pet has worrying symptoms, call the clinic before coming.",
  "Premier contact par téléphone": "First contact by phone",
  "Évaluation de la situation": "Assessment of the situation",
  "Orientation selon les besoins": "Guidance based on your pet's needs",
  "Interventions programmées ou d'urgence selon l'évaluation du vétérinaire.": "Scheduled or emergency procedures based on the veterinarian's assessment.",
  "Stérilisations & castrations": "Spaying and neutering",
  "Chirurgies abdominales": "Abdominal surgery",
  "Surveillance du réveil en douceur": "Careful recovery monitoring",
  "Des examens d'imagerie pour aider à comprendre l'état de santé de votre animal.": "Imaging tests to better understand your pet's health.",
  "Examens radiologiques": "Radiology examinations",
  "Exploration selon les besoins de l'animal": "Tests based on your pet's needs",
  "Interprétation vétérinaire": "Veterinary interpretation",
  "Examens biochimiques et hématologiques pour adapter le traitement sans délai.": "Biochemistry and blood tests to adjust treatment promptly.",
  "Bilan sanguin": "Blood tests",
  "Analyses biologiques adaptées": "Tailored laboratory tests",
  "Interprétation des résultats": "Interpretation of results",
  "Une prise en charge au cabinet lorsque l'état de votre compagnon nécessite des soins suivis.": "In-clinic care when your companion needs ongoing treatment.",
  "Suivi de l'état de santé": "Health monitoring",
  "Soins prescrits par le vétérinaire": "Veterinarian-prescribed care",
  "Informations aux propriétaires": "Updates for owners",
  "Prévention des affections bucco-dentaires et soulagement des douleurs gingivales.": "Prevention of dental disease and relief of gum pain.",
  "Détartrage aux ultrasons": "Ultrasonic scaling",
  "Polissage protecteur": "Protective polishing",
  "Extractions dentaires ciblées": "Targeted tooth extractions",
  "Des soins d'hygiène et d'entretien adaptés à votre compagnon.": "Grooming and hygiene tailored to your companion.",
  "Entretien du pelage": "Coat care",
  "Soins d'hygiène": "Hygiene care",
  "Conseils adaptés à l'animal": "Advice tailored to your pet",
  "Une solution de garde pour votre animal lorsque vous devez vous absenter.": "Boarding for your pet while you are away.",
  "Renseignements sur les disponibilités": "Availability information",
  "Prise en compte des besoins de l'animal": "Attention to your pet's needs",
  "Organisation avec le cabinet": "Arrangements with the clinic",
  "Appeler le cabinet": "Call the clinic",
  "Déroulement d'une visite": "How a visit works",
  "Comment se passe votre venue au cabinet ?": "What happens during your visit?",
  "Nous prenons le temps nécessaire avec chaque animal afin de minimiser le stress et": "We take the time each pet needs to reduce stress and",
  "bâtir une relation de confiance durable.": "build lasting trust.",
  "Nous prenons le temps nécessaire avec chaque animal afin de minimiser le stress et bâtir une relation de confiance durable.": "We take the time each pet needs to reduce stress and build lasting trust.",
  "Une décision de soin expliquée avec clarté": "Care decisions explained clearly",
  "Accueil & Écoute attentive": "Welcome and attentive listening",
  "Vous nous partagez l'historique de votre animal, ses habitudes et les symptômes observés.": "Tell us about your pet's history, habits and symptoms.",
  "Examen clinique complet": "Complete clinical examination",
  "Le praticien examine minutieusement votre compagnon avec douceur et méthode.": "The veterinarian examines your companion carefully and gently.",
  "Diagnostic & Décision partagée": "Diagnosis and shared decisions",
  "Nous vous expliquons les résultats et convenons ensemble du protocole de soin le plus adapté.": "We explain the results and agree on the most suitable care plan together.",
  "Urgences Marrakech": "Emergencies in Marrakech",
  "Votre animal nécessite une intervention immédiate ?": "Does your pet need immediate attention?",
  "Appelez le cabinet avant de vous déplacer afin que nous puissions vous orienter.": "Call the clinic before coming so we can guide you.",
  "Appeler le": "Call",
  // Contact page
  "Contact & Localisation": "Contact and location",
  "Nous sommes à votre écoute à Marrakech": "We are here to listen in Marrakech",
  "Une question sur la santé de votre animal, un besoin de conseil préventif ou une": "Have a question about your pet's health, need preventive advice or",
  "demande de renseignements ? Écrivez-nous ou rendez-nous visite.": "want more information? Message us or visit the clinic.",
  "Une question sur la santé de votre animal, un besoin de conseil préventif ou une demande de renseignements ? Écrivez-nous ou rendez-nous visite.": "Have a question about your pet's health, need preventive advice or want more information? Message us or visit the clinic.",
  "Nos coordonnées directes": "Contact details",
  "Pour toute urgence vitale, privilégiez toujours un appel direct avant de vous déplacer.": "For life-threatening emergencies, always call before coming.",
  "Téléphone & Urgences": "Phone and emergencies",
  "Canal WhatsApp": "WhatsApp",
  "Écrire directement sur WhatsApp": "Message us directly on WhatsApp",
  "Adresse de la clinique": "Clinic address",
  "Horaires d'ouverture": "Opening hours",
  "Horaires à confirmer par téléphone. En cas d'urgence, appelez avant de venir.": "Please confirm opening hours by phone. In an emergency, call before coming.",
  "Carte du Cabinet Vétérinaire Atlas Marrakech": "Map of Atlas Veterinary Clinic Marrakech",
  "Ouvrir l’itinéraire sur Google Maps": "Get directions on Google Maps",
  // Appointment page
  "Cabinet Vétérinaire Atlas · Marrakech": "Atlas Veterinary Clinic · Marrakech",
  "Remplissez le formulaire ci-dessous ou contactez-nous directement. Nous vous confirmons votre rendez-vous dans les plus brefs délais.": "Complete the form below or contact us directly. We will confirm your appointment as soon as possible.",
  "Remplissez le formulaire ci-dessous ou contactez-nous directement.": "Complete the form below or contact us directly.",
  "Nous vous confirmons votre rendez-vous dans les plus brefs délais.": "We will confirm your appointment as soon as possible.",
  "Téléphone": "Phone",
  "Urgences 24h/7j": "24/7 emergencies",
  "Adresse": "Address",
  "Marrakech, Maroc": "Marrakech, Morocco",
  "Quartier Guéliz": "Guéliz district",
  "Horaires": "Hours",
  "Ouvert tous les jours": "Open every day",
  "Comment réserver": "How to book",
  "Comment ça marche ?": "How does it work?",
  "1. Choisissez un créneau": "1. Choose a time slot",
  "Consultez les disponibilités proposées.": "View the available times.",
  "2. Envoyez votre demande": "2. Send your request",
  "Renseignez les informations utiles pour votre visite.": "Provide the information needed for your visit.",
  "3. Attendez la confirmation": "3. Wait for confirmation",
  "Le cabinet vous recontacte pour confirmer.": "The clinic will contact you to confirm.",
  "Appelez directement le": "Call",
  "avant de venir.": "before coming.",
  // Forms and feedback
  "Votre demande": "Your request",
  "Les champs marqués * sont obligatoires.": "Fields marked * are required.",
  "Vos coordonnées": "Your details",
  "Nom complet *": "Full name *",
  "Téléphone *": "Phone *",
  "Votre animal": "Your pet",
  "Nom de l’animal *": "Pet's name *",
  "Espèce *": "Species *",
  "Choisir": "Select",
  "Chien": "Dog",
  "Chat": "Cat",
  "Oiseau": "Bird",
  "Lapin": "Rabbit",
  "Rongeur": "Rodent",
  "Reptile": "Reptile",
  "Autre": "Other",
  "Race": "Breed",
  "Âge": "Age",
  "Ex. 3 ans": "E.g. 3 years",
  "Le rendez-vous": "The appointment",
  "Service *": "Service *",
  "Date souhaitée *": "Preferred date *",
  "Heure *": "Time *",
  "Chargement…": "Loading…",
  "Aucun créneau": "No available slots",
  "Message ou symptômes": "Message or symptoms",
  "Demande envoyée. Nous vous contacterons pour la confirmer.": "Request sent. We will contact you to confirm it.",
  "Envoi impossible. Vous pouvez nous contacter directement par WhatsApp.": "Could not send your request. You can contact us directly on WhatsApp.",
  "Envoi…": "Sending…",
  "Envoyer la demande": "Send request",
  "Réserver via WhatsApp": "Book via WhatsApp",
  "Envoyer un message": "Send a message",
  "Sujet *": "Subject *",
  "Votre message *": "Your message *",
  "Votre message a bien été envoyé.": "Your message was sent successfully.",
  "L’envoi a échoué. Appelez-nous au 06 62 12 08 78.": "Sending failed. Call us on 06 62 12 08 78.",
  "Envoyer le message": "Send message",
  "Indiquez votre nom.": "Enter your name.",
  "Numéro de téléphone invalide.": "Invalid phone number.",
  "Adresse email invalide.": "Invalid email address.",
  "Email invalide.": "Invalid email address.",
  "Indiquez le nom de l’animal.": "Enter your pet's name.",
  "Choisissez une espèce.": "Choose a species.",
  "Choisissez un service.": "Choose a service.",
  "Choisissez une date.": "Choose a date.",
  "Choisissez une heure.": "Choose a time.",
  "Indiquez un sujet.": "Enter a subject.",
  "Votre message doit contenir au moins 10 caractères.": "Your message must have at least 10 characters.",
};
